[build]
  base = ""  # Laisse vide ou supprime cette ligne
  publish = "site"  # Netlify publiera les fichiers à partir du dossier site/
  command = ""

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200